server:
  port: 8081

spring:
  application:
    name: RealTimeCommunicationService
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:127.0.0.1:9092}
    consumer:
      group-id: rtc-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

netty:
  port: 9090
  path: /ws
